<?xml version="1.0"?>
<clause number="23.1" title="Causas de excepciones">
<paragraph>Las excepciones pueden ser lanzadas de dos maneras diferentes. <list><list_item> Una sentencia throw (<hyperlink>15.9.5</hyperlink>) lanza una excepción inmediatamente y en forma incondicional. La sentencia inmediatamente después del lanzamiento de la excepción nunca se llega a ejecutar.</list_item><list_item> Ciertas condiciones excepcionales que se presentan al procesar sentencias y expresiones de C# causan una excepción en ciertas circunstancias cuando la operación no puede ser completada totalmente. Por ejemplo, una operación de división entera (<hyperlink>14.7.2</hyperlink>) lanza una excepción de tipo System.DivideByZeroException si el denominador es cero. Ver la sección<hyperlink>23.4</hyperlink> para obtener una lista de las varias excepciones que pueden ocurrir de esta manera.</list_item></list></paragraph>
</clause>
<!-- Traducido por Antonio Ognio <aognio@gmail.com> -->
